# conda / mamba env update -f environment.yml

name: toy

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - cpuonly
  - pip
  - numpy
  - pytorch
  - torchvision

  - pip:
      - coverage
